substitutions:
  devicename: test_sensors
  co2_name: test
  
esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    platform: "espressif8266@2.5.3"
    upload_speed: 460800

wifi:
  ssid: !secret ap_name
  password: !secret ap_password
  fast_connect: true

  ap:
    ssid: "Hotspot $devicename"
    password: !secret hotspot_password

captive_portal:

logger:
  baud_rate: 0

api:
  password: !secret api_password

ota:
  password: !secret ota_password

uart:
    rx_pin: D7
    tx_pin: D8
    baud_rate: 9600

sensor:
  - platform: uptime
    name: "$devicename uptime"
  - platform: senseair
    co2:
      name: "$co2_name co2"
    update_interval: 30s

switch:
  - platform: gpio
    name: "$devicename cal"
    pin:
      number: D6
      inverted: True
    restore_mode: ALWAYS_OFF